name: audio_therapy_app
description: AURA â€“ Audio-Visual Bio-Interface for Symbiotic Resonance

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  shared_preferences: ^2.3.0
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  shaders:
    - lib/src/layers/neuro_optical/shaders/motion_aftereffect.frag

  assets:
    - assets/sounds/inner/ambient_default.mp3
    - assets/sounds/inner/binaural_528.mp3
    - assets/sounds/middle/cat_purr.mp3
    - assets/sounds/outer/ultrasonic_18khz.mp3